In [4]:
import pandas as pd
df=pd.read_csv("/content/student2.txt",sep="\t")

In [5]:
df

               student_id  name  Dept  Marks
100 Rupak             CSE    75   NaN    NaN
101 Ravi               ME    45   NaN    NaN
102 Kishan             IT    50   NaN    NaN
103 Yug               CSE    80   NaN    NaN
104 Sachin             IT    83   NaN    NaN
105 Vishwadeep        CSE    87   NaN    NaN

# **Create a TSV File**

In [6]:
tsv_text="""student_id\tName\tDepartment\tAttendance\tMarks
101\tAman\tCSE\t92\t85
102\tPriya\tIT\t96\t92
103\tRahul\tCSE\t\t76
104\tSara\tESE\t88\t89
103\tNeha\tIT\t79\t
103\tVikram\tCSE\t91\t81
"""

with open("students_updated.tsv","w",encoding="utf-8") as file:
  file.write(tsv_text)
  print("TSV file created successfully.")

TSV file created successfully.

In [20]:
df=pd.read_csv("/content/students_updated.tsv",sep="\t")

# **Inspect dataset**

In [21]:
display(df.head())

   student_id   Name Department  Attendance  Marks
0         101   Aman        CSE        92.0   85.0
1         102  Priya         IT        96.0   92.0
2         103  Rahul        CSE         NaN   76.0
3         104   Sara        ESE        88.0   89.0
4         103   Neha         IT        79.0    NaN

In [22]:
print("Dataset shape(rows,columns):",df.shape)

Dataset shape(rows,columns): (6, 5)

In [23]:
print("Column names:",df.columns.tolist())

Column names: ['student_id', 'Name', 'Department', 'Attendance', 'Marks']

In [24]:
print("Data types:")
print(df.dtypes)

Data types:
student_id      int64
Name           object
Department     object
Attendance    float64
Marks         float64
dtype: object

In [25]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
student_id    0
Name          0
Department    0
Attendance    1
Marks         1
dtype: int64

# **Select and Filter data**

In [26]:
display(df["Name"])

0      Aman
1     Priya
2     Rahul
3      Sara
4      Neha
5    Vikram
Name: Name, dtype: object

In [27]:
display(df[["Name","Marks"]])

     Name  Marks
0    Aman   85.0
1   Priya   92.0
2   Rahul   76.0
3    Sara   89.0
4    Neha    NaN
5  Vikram   81.0

In [29]:
display(df[df["Marks"]>80])

   student_id    Name Department  Attendance  Marks
0         101    Aman        CSE        92.0   85.0
1         102   Priya         IT        96.0   92.0
3         104    Sara        ESE        88.0   89.0
5         103  Vikram        CSE        91.0   81.0

In [30]:
display(df[df["Department"]=="CSE"])

   student_id    Name Department  Attendance  Marks
0         101    Aman        CSE        92.0   85.0
2         103   Rahul        CSE         NaN   76.0
5         103  Vikram        CSE        91.0   81.0

# **Handle missing values**

In [31]:
print(df.isna().sum())

student_id    0
Name          0
Department    0
Attendance    1
Marks         1
dtype: int64

In [33]:
df_drop=df.dropna()
display(df_drop)

   student_id    Name Department  Attendance  Marks
0         101    Aman        CSE        92.0   85.0
1         102   Priya         IT        96.0   92.0
3         104    Sara        ESE        88.0   89.0
5         103  Vikram        CSE        91.0   81.0

In [34]:
df_fill=df.copy()
df_fill["Attendance"]=df_fill["Attendance"].fillna(df_fill["Attendance"].median())

In [35]:
df_fill["Marks"]=df_fill["Marks"].fillna(df_fill["Marks"].median())

In [36]:
display(df_fill)

   student_id    Name Department  Attendance  Marks
0         101    Aman        CSE        92.0   85.0
1         102   Priya         IT        96.0   92.0
2         103   Rahul        CSE        91.0   76.0
3         104    Sara        ESE        88.0   89.0
4         103    Neha         IT        79.0   85.0
5         103  Vikram        CSE        91.0   81.0

In [37]:
print("Summart statistics:")
display(df_fill[["Attendance","Marks"]].describe())

Summart statistics:

       Attendance      Marks
count     6.00000   6.000000
mean     89.50000  84.666667
std       5.75326   5.680376
min      79.00000  76.000000
25%      88.75000  82.000000
50%      91.00000  85.000000
75%      91.75000  88.000000
max      96.00000  92.000000

In [38]:
display(df_fill.groupby("Department")["Marks"].mean())

Department
CSE    80.666667
ESE    89.000000
IT     88.500000
Name: Marks, dtype: float64

In [39]:
display(df_fill["Department"].value_counts())

Department
CSE    3
IT     2
ESE    1
Name: count, dtype: int64

In [40]:
df_fill.to_csv("students_cleaned.tsv",sep="\t",index=False)
print("cleaned tsv saved")

cleaned tsv saved

In [41]:
check_df=pd.read_csv("students_cleaned.tsv",sep="\t")
display(check_df)

   student_id    Name Department  Attendance  Marks
0         101    Aman        CSE        92.0   85.0
1         102   Priya         IT        96.0   92.0
2         103   Rahul        CSE        91.0   76.0
3         104    Sara        ESE        88.0   89.0
4         103    Neha         IT        79.0   85.0
5         103  Vikram        CSE        91.0   81.0

In [42]:
with open("students_cleaned.tsv","r", encoding="utf-8") as file:
  print(file.read())

student_id	Name	Department	Attendance	Marks
101	Aman	CSE	92.0	85.0
102	Priya	IT	96.0	92.0
103	Rahul	CSE	91.0	76.0
104	Sara	ESE	88.0	89.0
103	Neha	IT	79.0	85.0
103	Vikram	CSE	91.0	81.0

# **Practice Questions**
(1-10)

Q1

In [43]:
import pandas as pd

data = {
    "StudentID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Aman", "Riya", "Rahul", "Priya",
             "Karan", "Neha", "Arjun", "Sneha"],
    "Department": ["CSE", "IT", "CSE", "ECE",
                   "IT", "CSE", "ECE", "IT"],
    "Attendance": [90, 82, 88, 95, 75, 91, 85, 89],
    "Marks": [85, 78, 92, 88, 67, 95, 80, 84]
}

df = pd.DataFrame(data)

df.to_csv("students.tsv", sep="\t", index=False)

print(df)

   StudentID   Name Department  Attendance  Marks
0        101   Aman        CSE          90     85
1        102   Riya         IT          82     78
2        103  Rahul        CSE          88     92
3        104  Priya        ECE          95     88
4        105  Karan         IT          75     67
5        106   Neha        CSE          91     95
6        107  Arjun        ECE          85     80
7        108  Sneha         IT          89     84

Q2

In [45]:

df = pd.read_csv("students.tsv", sep="\t")

print(df.head(3))

   StudentID   Name Department  Attendance  Marks
0        101   Aman        CSE          90     85
1        102   Riya         IT          82     78
2        103  Rahul        CSE          88     92

Q3

In [46]:
print("Number of rows and columns:", df.shape)
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows and columns: (8, 5)
Number of rows: 8
Number of columns: 5

Q4

In [47]:
print(df[["Name", "Marks"]])

    Name  Marks
0   Aman     85
1   Riya     78
2  Rahul     92
3  Priya     88
4  Karan     67
5   Neha     95
6  Arjun     80
7  Sneha     84

Q5

In [48]:
print(df[df["Attendance"] >= 85])

   StudentID   Name Department  Attendance  Marks
0        101   Aman        CSE          90     85
2        103  Rahul        CSE          88     92
3        104  Priya        ECE          95     88
5        106   Neha        CSE          91     95
6        107  Arjun        ECE          85     80
7        108  Sneha         IT          89     84

Q6

In [49]:
print(df["Department"].value_counts())

Department
CSE    3
IT     3
ECE    2
Name: count, dtype: int64

Q7

In [50]:
print(df.groupby("Department")["Marks"].mean())

Department
CSE    90.666667
ECE    84.000000
IT     76.333333
Name: Marks, dtype: float64

Q8

In [51]:
df.loc[0, "Marks"] = None

print(df)

   StudentID   Name Department  Attendance  Marks
0        101   Aman        CSE          90    NaN
1        102   Riya         IT          82   78.0
2        103  Rahul        CSE          88   92.0
3        104  Priya        ECE          95   88.0
4        105  Karan         IT          75   67.0
5        106   Neha        CSE          91   95.0
6        107  Arjun        ECE          85   80.0
7        108  Sneha         IT          89   84.0

method1

In [52]:
df1 = df.dropna()
print(df1)

   StudentID   Name Department  Attendance  Marks
1        102   Riya         IT          82   78.0
2        103  Rahul        CSE          88   92.0
3        104  Priya        ECE          95   88.0
4        105  Karan         IT          75   67.0
5        106   Neha        CSE          91   95.0
6        107  Arjun        ECE          85   80.0
7        108  Sneha         IT          89   84.0

method 2

In [53]:
df2 = df.copy()

df2["Marks"] = df2["Marks"].fillna(df2["Marks"].mean())

print(df2)

   StudentID   Name Department  Attendance      Marks
0        101   Aman        CSE          90  83.428571
1        102   Riya         IT          82  78.000000
2        103  Rahul        CSE          88  92.000000
3        104  Priya        ECE          95  88.000000
4        105  Karan         IT          75  67.000000
5        106   Neha        CSE          91  95.000000
6        107  Arjun        ECE          85  80.000000
7        108  Sneha         IT          89  84.000000

Q9

In [54]:
df2.to_csv("cleaned_students.tsv", sep="\t", index=False)

print("Cleaned data saved successfully")

Cleaned data saved successfully

Q10

In [55]:
df3 = pd.read_csv("cleaned_students.tsv", sep="\t")

print("Column names:")
print(df3.columns)

print("Shape:")
print(df3.shape)

Column names:
Index(['StudentID', 'Name', 'Department', 'Attendance', 'Marks'], dtype='object')
Shape:
(8, 5)